### ISSUE TITLE
Error in segmentation.py which hinders downstream analysis (`membrane_img_orig = None`) 

### ISSUE THREAD

**Issue by nimarafati** [CellProfiling/pipex#2]
Hi,

In one run **preprocessing** passed and the pipeline failed at **segmentation**.  

Here are the commands:
- Preprocessing:   
`preprocessing.py -data=exported_channels_2 -threshold_min=0 -threshold_max=100 -exposure=100 -heat_map=no`. 
- Segmentation:  
`segmentation.py -data=exported_channels_2 -nuclei_marker=DAPI -nuclei_diameter=20 -nuclei_expansion=20 -nuclei_definition=0 -nuclei_closeness=0 -nuclei_area_limit=0 -adjust_images=no -membrane_marker=Pan-Cytokeratin,b-Catenin1 -membrane_diameter=25 -membrane_compactness=0.9 -membrane_keep=no -measure_markers=CD68,Her2`.  

I looked a bit in the code and apparently the `downscale_images` function does not return a resized `np_img` which by default is `None`.   

And the error:  
```checking type of /Users/nimra236/Dropbox/NBIS/Projects/Spatial/data/Spatial_Proteomics/exported_channels/.DS_Store, not QPTIFF
>>>  not a TIFF file b'\x00\x00\x00\x01'
>>> checking type of /Users/nimra236/Dropbox/NBIS/Projects/Spatial/data/Spatial_Proteomics/exported_channels/log.txt, not QPTIFF
>>>  not a TIFF file b'Mac '
Traceback (most recent call last):
  File "/Users/nimra236/Dropbox/git/pipex_forked/segmentation.py", line 471, in <module>
    cellLabels = cell_segmentation(nuclei_img, membrane_img)
  File "/Users/nimra236/Dropbox/git/pipex_forked/segmentation.py", line 94, in cell_segmentation
    membrane_img = (membrane_img_orig - np.amin(membrane_img_orig)) / (np.amax(membrane_img_orig) - np.amin(membrane_img_orig))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType' ```
.

**Comment by OmFrederic** [comment]
Hello,
   
   First of all, that PIPEX trace is not informative at all, my bad. Then my guess is that there was a problem with the part of the `segmentation.py` script reading the nuclei and/or the membrane images, so they were not properly informed and remained as `None`. Could you please verify the file names?
   
   As for the ` downscale_images` method, it should return either the resized image or the original image, so you should never end up with a `None` result unless the input image was already `None`

**Comment by cavenel** [comment]
Hi @nimarafati and @OmFrederic,

I see that you used two markers for the membrane (Pan-Cytokeratin and b-Catenin1). Looking at the code, I'm not sure if this is supported in PIPEX. Could you test with only one marker here?
I believe that PIPEX is trying to find the image `Pan-Cytokeratin,b-Catenin1.tif` and failing to do so.

**Comment by nimarafati** [comment]
Hi @OmFrederic and @cavenel,
Thanks for your feedbacks, it was indeed passing two membrane markers. After setting only one marker it worked fine!
