### ISSUE TITLE
Measuring expression of membrane marker

### ISSUE THREAD

**Issue by nimarafati** [CellProfiling/pipex#5]
Hi,

While setting the membrane marker, the workflow complains if I include the membrane marker together with other markers. As a solution I duplicate the membrane marker and rename it. But I was wondering if it has been implemented in a way not to measure the expression of membrane marker?

Regards,

**Comment by OmFrederic** [comment]
Hello nimarafati! 

Sorry for the delay in my answer, I seldom look this section, my bad. The membrane marker used for the segmentation does not need to be in the measure markers. Actually is not uncommon to use a nuclear and membrane image pre-processed by some means to get a better segmentation and THEN don't measure them at all. 

I just tried right now and works. Maybe it has been fixed along the way?

Frederic
